# Generated by Django 2.1.7 on 2019-02-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='phone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
