# Generated by Django 2.1.7 on 2019-02-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190213_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
